# Generated by Django 5.2.8 on 2025-12-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
