# Generated by Django 5.2.6 on 2025-12-02 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('p', 'Pending'), ('r', 'Read')], default='p', help_text='Notification Status', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partnership_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='partnerships.partnership')),
                ('sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='partnerships.department')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
