# Generated by Django 5.2.8 on 2025-12-03 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('partnerships', '0002_alter_partnership_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='partnership_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partnerships.partnership'),
        ),
    ]
