# Generated by Django 5.2.8 on 2025-12-03 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='department-logo/')),
                ('status', models.CharField(blank=True, choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='Department Status', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partnership-logo/')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('started_date', models.DateField()),
                ('effectivity_date', models.DateField()),
                ('status_tag', models.CharField(blank=True, choices=[('a', 'Active'), ('r', 'For Renewal'), ('t', 'Terminated'), ('e', 'Expired')], default='a', help_text='Partnership Status', max_length=1)),
                ('school_year', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_type', models.CharField(choices=[('local', 'Local'), ('international', 'International')], default='local', help_text='Indicates whether the partnership is local or international', max_length=20)),
                ('department_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='partnerships.department')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effectivity_date', models.DateField(blank=True, null=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='partnerships.partnership')),
            ],
        ),
    ]
