# Generated by Django 5.2.8 on 2025-12-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='partnerships', to='partnerships.department'),
        ),
    ]
